services:

  postgres:
    image: postgres:16
    container_name: syssleuth-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: syssleuth_inventory

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  order-service:
    build: ./order-service
    container_name: order-service
    restart: unless-stopped

    ports:
      - "8001:8001"

    depends_on:
      - postgres


  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    restart: unless-stopped
    

    ports:
      - "8002:8002"

    depends_on:
      - postgres


  payment-service:
    build: ./payment-service
    container_name: payment-service
    restart: unless-stopped

    ports:
      - "8003:8003"

    depends_on:
      - postgres


  product-service:
    build: ./product-service
    container_name: product-service
    restart: unless-stopped

    ports:
      - "8004:8004"

    depends_on:
      - postgres

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: syssleuth_inventory
      DB_USER: postgres
      DB_PASSWORD: password123


volumes:
  postgres_data: